### ISSUE TITLE
Easily copy image of diagram

### ISSUE THREAD

**Issue by cbertram** [yishn/tikzcd-editor#63] opened 2020-11-24 09:48 UTC
This is a feature request.

When chatting with people, or otherwise using diagrams outside of a TeX document, I like to jump into the tikzcd-editor, set up a diagram and then just take a screenshot. Before doing so, I open the CSS-editor in my browser and disable the dashed lines around the background squares, to get a white background, as if the diagram was taken right out of a TeX document. It would be nice if there was a button to instantly copy a perfect "screenshot" to the clipboard.

I am not sure how to implement this myself, but would like to help, if it seems easy and you can point me in the right direction.

**Comment by yishn** [comment] 2020-11-24 10:21
Duplicate of #25.

**Closed as completed by yishn** 2020-11-24 10:21 UTC
Labels: duplicate
