### ISSUE TITLE
Order of commands

### ISSUE THREAD

**Issue by edelopo** [yishn/tikzcd-editor#62] opened 2020-11-07 20:36 UTC
I just tried to create a diagram with "long equals signs" between nodes. To do this I used the double arrow and removed the head. However, the output code gives the \arrow options in the following order:

 \arrow[dd, no head, Rightarrow]

The Right arrow overrides the no head. Changing the order to:

\arrow[dd, Rightarrow, no head]

solves the problem.

**Comment by yishn** [comment] 2020-11-22 12:13
This is duplicate of #47 and should be fixed by #58 in the next release.

**Closed as completed by yishn** 2020-11-22 12:13 UTC
Labels: duplicate
